
STATUS_500_MSG = "Something went wrong !!"
STATUS_404_MSG = "Please try again"
INVALID_OTP = "Invalid OTP, Please try again"
USER_NOT_FOUND = "User doesn't exists."
PROFILE_NOT_UPDATED = "User profile not updated."
INVALID_CREDENTIALS = "Invalid credentials"
MAX_GROUP_CREATION_REACHED = "You have reached group creation limit. Please upgrade"
GROUP_NOT_CREATED = "Group not created. Please try again later"
GROUP_CREATED = "Group Created."
INVALID_JOIN_LINK = "Invalid Join link."
ALREADY_MEMBER_OF_GROUP = "You are already a member of this group"
ADDED_TO_GROUP = "You are added to the group."
CANT_UPDATE_GROUP_JOIN_LINK = "You dont have permission to update join link."
GROUP_JOIN_LINK_UPDATED = "Group join link updated"